name: stacked_chart
description: A simple package which provide easy way to generate stacked bar chart.
version: 0.0.5
repository: https://github.com/Bikram-Shrestha/stacked_chart

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

